#!/bin/sh

./deploy $1

LOCAL_ROOT=../
PACKAGE=$1
PACKAGE_HOST="hs1@127.0.0.1"
PACKAGE_PORT=2222
PACKAGES_DIR=../../packages/
PACKAGE_DIR=$PACKAGES_DIR$PACKAGE
PACKAGE_CONFIGS_DIR=$LOCAL_ROOT/package-configs/

echo "Remote deploy"

DATE=$(date --iso)
rm -f /tmp/tmp.tgz
PPWD=$PWD
cd $PACKAGE_DIR
tar zcf /tmp/tmp.tgz *
cd $PPWD
scp -P $PACKAGE_PORT /tmp/tmp.tgz $PACKAGE_HOST:/tmp/tmp.tgz
ssh -p $PACKAGE_PORT $PACKAGE_HOST mkdir -p /home/hs1/hs2-deploy/$PACKAGE/$DATE
ssh -p $PACKAGE_PORT $PACKAGE_HOST tar zxf /tmp/tmp.tgz -C /home/hs1/hs2-deploy/$PACKAGE/$DATE
ssh -p $PACKAGE_PORT $PACKAGE_HOST rm -f /home/hs1/hs2-current-deploy/$PACKAGE
ssh -p $PACKAGE_PORT $PACKAGE_HOST ln -s /home/hs1/hs2-deploy/$PACKAGE/$DATE /home/hs1/hs2-current-deploy/$PACKAGE
