#!/bin/bash

. settings

if [ $PACKAGE_HOST == "local" ];
then
    echo "This is local config, will note deploy to remote"
    exit 0;
fi

PACKAGE=$1

./make $PACKAGE

echo "Pushing to: $PACKAGE_HOST"

DATE=$(date --iso)
rm -f /tmp/tmp.tgz
PPWD=$PWD
cd $PACKAGE_DIR
tar zcf /tmp/tmp.tgz *
cd $PPWD
scp /tmp/tmp.tgz $PACKAGE_HOST:/tmp/tmp.tgz
ssh $PACKAGE_HOST mkdir -p $DEPLOY_PATH/$PACKAGE/$DATE
ssh $PACKAGE_HOST tar zxf /tmp/tmp.tgz -C $DEPLOY_PATH/$PACKAGE/$DATE
ssh $PACKAGE_HOST rm -f $CURRENT_DEPLOY_PATH/$PACKAGE
ssh $PACKAGE_HOST ln -s $DEPLOY_PATH/$PACKAGE/$DATE $CURRENT_DEPLOY_PATH/$PACKAGE
