#!/bin/sh
#
# usage: $0 PACKAGE MACHINE SCRIPT

LOCAL_ROOT=../
PACKAGE=$1
MACHINE=$2
SCRIPT=$3
FOLDER=$4

ssh -t hs1@flareon "cd hs2-current-deploy/script-zero-trace-flareon/client; screen -S $MACHINE sh -c \"cd .; ./fuzzer.py --out-prefix $FOLDER $MACHINE $SCRIPT; bash\""
