#!/bin/sh

./deploy $1

LOCAL_ROOT=../
TARGET=$1
TARGET_HOST="hs1@127.0.0.1"
TARGET_PORT=2222
TARGETS_DIR=../../targets/
TARGET_DIR=$TARGETS_DIR$TARGET
TARGET_CONFIGS_DIR=$LOCAL_ROOT/target-configs/

echo "Remote deploy"

DATE=$(date --iso)
rm -f /tmp/tmp.tgz
PPWD=$PWD
cd $TARGET_DIR
tar zcf /tmp/tmp.tgz *
cd $PPWD
scp -P $TARGET_PORT /tmp/tmp.tgz $TARGET_HOST:/tmp/tmp.tgz
ssh -p $TARGET_PORT $TARGET_HOST mkdir -p /home/hs1/hs2-deploy/$TARGET/$DATE
ssh -p $TARGET_PORT $TARGET_HOST tar zxf /tmp/tmp.tgz -C /home/hs1/hs2-deploy/$TARGET/$DATE
ssh -p $TARGET_PORT $TARGET_HOST rm -f /home/hs1/hs2-current-deploy/$TARGET
ssh -p $TARGET_PORT $TARGET_HOST ln -s /home/hs1/hs2-deploy/$TARGET/$DATE /home/hs1/hs2-current-deploy/$TARGET
