#!/bin/sh

./deploy $1

LOCAL_ROOT=../
TARGET=$1
TARGET_HOST="hs1@10.8.0.6"
TARGETS_DIR=../../targets/
TARGET_DIR=$TARGETS_DIR$TARGET
TARGET_CONFIGS_DIR=$LOCAL_ROOT/target-configs/
DEPLOY_PATH=/home/ish/kor-pro/hs2-deploy/

echo "Local deploy"

DATE=$(date --iso)
rm -rf $DEPLOY_PATH$TARGET/$DATE
mkdir -p $DEPLOY_PATH$TARGET/$DATE
cp -r $TARGET_DIR/* $DEPLOY_PATH$TARGET/$DATE/
rm -f /home/ish/kor-pro/hs2-current-deploy/$TARGET
ln -s $DEPLOY_PATH$TARGET/$DATE /home/ish/kor-pro/hs2-current-deploy/$TARGET

echo "Copying secondary disk template"
cp ../../../blob/raw-imgs/1/secondary.raw /home/ish/kor-pro/hs2-current-deploy/$TARGET
