#!/bin/bash

. settings

PACKAGE=$1
PACKAGE_DIR=$PACKAGES_DIR/$PACKAGE

./make $PACKAGE

if [ $PACKAGE_HOST != "local" ];
then
    echo "Pushing to remote host: $PACKAGE_HOST"
    ./push-remote $PACKAGE
else
    echo "Local deploy started"

    DATE=$(date --iso)
    rm -rf $DEPLOY_PATH/$PACKAGE/$DATE
    mkdir -p $DEPLOY_PATH/$PACKAGE/$DATE
    cp -r $PACKAGE_DIR/* $DEPLOY_PATH/$PACKAGE/$DATE/
    rm -f $CURRENT_DEPLOY_PATH/$PACKAGE
    ln -s $DEPLOY_PATH/$PACKAGE/$DATE $CURRENT_DEPLOY_PATH/$PACKAGE

    echo "Local deploy finished"
fi
