#!/bin/sh
#
# usage: $0 TARGET MACHINE SCRIPT

LOCAL_ROOT=../
TARGET=$1
MACHINE=$2
SCRIPT=$3
FOLDER=$4

./deploy-remote $1

ssh -t hs1@flareon "cd hs2-current-deploy/$TARGET/client; screen -L -S $MACHINE sh -c \"cd .; ./fuzzer.py $MACHINE $SCRIPT $FOLDER; bash\""
