#!/bin/sh
SRC=$1
DST=$2
OFFSET=$3
OFFSET=32256
TMPDIR=$(mktemp -d)
echo "Extrating from $SRC into $DST"
mkdir -p $DST

if [ $OFFSET ]
then
    sudo mount -o offset=$OFFSET $SRC $TMPDIR
else
    sudo mount $SRC $TMPDIR
fi

cp -r $TMPDIR/* $DST
sudo umount $TMPDIR
rm -rf $TMPDIR
