#!/usr/bin/env python

import sys

if(len(sys.argv) < 2):
    exit

map_path = sys.argv[1]

my_map = open(map_path, "r")

for line in my_map:
    if(line.find('/map') != -1):
        break

for line in my_map:
    print line[:-1]

my_map.seek(0, 0)

for line in my_map:
    if(line.find('/map') != -1):
        print line[:-1]
        break
    print line[:-1]

my_map.close()
