#!/bin/sh
#
# usage: $0 FOLDER MAP

LOCAL_ROOT=../
REMOTE_ROOT="/mnt/1/output"
FOLDER=$1
MAP=$2

mkdir -p $1
echo "Retrieving remote render..."
scp hs1@flareon:$REMOTE_ROOT/$FOLDER/$MAP $1/$MAP".tmp"
echo "Restructurizing..."
fix-map $1/$MAP".tmp" 1> $1/$MAP
echo "Removing temp file..."
rm $1/$MAP".tmp"
