PrintLogo
GetOptions
GetSampleOptions
RevertClean
EnableLogging
RegisterSignals
PrepareStats
PreparePipes
ChooseSavedMethod=(AM:AutogeneratedMethod,GM:GlobMethod)

AutogeneratedMethod:
AutogeneratedMethod
AutogeneratedDisk
StartQemuFull
goto(startController)

GlobMethod:
GlobMethod
DiskGlob
StartQemuFull

QemuMountDisks

start_controller:
SpawnInternalController
QemuConnectDevSocket
IsSocketConnected=(Y:success,N:fail)

fail:
Wait10
goto(start_controller)

success:
KillExplorer
ResetTracers
SpawnTracerController
SpawnTracerLog
TracerConfigureSample
TracerConfigureOutDir
TracerConfigureOutPrefix
TracerConfigureInDir
TracerPrepareTrace
TracerRegisterRegions
TracerRegisterReactions
DisableReactions
TracerDebugSample
TracerDebugContinueInf

decision:
Decision=(RR:proc_started,RE:exception,ST:start_trace)

proc_started:
EnableReaction(A1)
TracerDebugContinueInf
goto(decision)

exception:
TracerDebugContinueInf(0x80010001)
goto(decision)

start_trace:
EnableReaction(S1)
DumpMemory
TracerStartTrace
TracerDebugContinueInf
goto(decision)

finish:
