EnableReaction(C1)
EnableReaction(C3)
EnableReaction(C5)
EnableReaction(C7)
EnableReaction(C9)
EnableReaction(D1)
EnableReaction(T1)
EnableReaction(R1)

RaiseReaction(C1)
RaiseReaction(C3)
RaiseReaction(C5)
RaiseReaction(C7)
RaiseReaction(C9)
RaiseReaction(D1)
RaiseReaction(T1)
RaiseReaction(R1)
