PrintLogo
GetOptions
GetSampleOptions
RevertClean
EnableLogging
RegisterSignals
PrepareStats
PreparePipes
ChooseSavedMethod=(AM:AutogeneratedMethod,GM:GlobMethod)

AutogeneratedMethod:
AutogeneratedMethod
AutogeneratedDisk
StartQemuFull
goto(startController)

GlobMethod:
GlobMethod
DiskGlob
StartQemuFull

QemuMountDisks

start_controller:
SpawnInternalController
QemuConnectDevSocket
IsSocketConnected=(Y:success,N:fail)

fail:
Wait10
goto(start_controller)

success:
KillExplorer
ResetTracers
SpawnTracerController
SpawnTracerLog
TracerConfigureSample
TracerConfigureOutDir
TracerConfigureOutPrefix
TracerConfigureInDir
TracerPrepareTrace
TracerRegisterRegions
TracerRegisterReactions
DisableReactions
TracerDebugSample
TracerDebugContinueInf

decision:
Decision=(RR:proc_started,RE:exception,ST:start_trace,C1:created_process,C3:created_process,C2:extract_pid,C4:extract_pid,T1:set_context,EN:tracer_finished)

proc_started:
EnableReaction(A1)
TracerDebugContinueInf
goto(decision)

exception:
TracerDebugContinueInf(0x80010001)
goto(decision)

start_trace:
EnableReaction(C1)
EnableReaction(C3)
DumpMemory
TracerStartTrace
TracerDebugContinueInf
goto(decision)

created_process:
# handle CreateProcessX
ReadRegister(ESP)
Adjust(0x18)
ReadDword
CheckEqual(0x00000004)=(Y:with_suspension,N:without_suspension)

without_suspension:
ReadRegister(ESP)
Adjust(0x18)
WriteDword(0x00000004)
# get EP and attach immidiately
goto(attach_auto_st)

with_suspension:
# in order to receive EP
# attach after writing memory and setting EIP
EnableReaction(T1)
TracerDebugContinueInf
goto(decision)

extract_pid:
# get PROCESS_INFORMATION and read PID & TID
ReadRegister(ESP)
Adjust(0x28)
ReadDword
Adjust(0x8)
ReadPID
ReadRegister(ESP)
Adjust(0x28)
ReadDword
Adjust(0xc)
ReadTID
TracerDebugContinueInf
goto(decision)

set_context:
# get CONTEXT
ReadRegister(ESP)
Adjust(0x8)
ReadDword
# extract EIP
#Adjust(0xb0)
Adjust(0xb8)
ReadEP
goto(attach)

attach_auto_st:
# spawn another tracer
SpawnTracerLog
TracerConfigureSamplePID
TracerConfigureOutDir
TracerConfigureOutPrefix
TracerConfigureInDir
TracerPrepareTrace
TracerRegisterRegions
TracerRegisterReactions
DisableReactions
TracerDebugSample
AutoST
# this should be TracerNext?
# resume thread
TracerPrev
TracerDebugContinueInf
goto(decision)

attach:
# spawn another tracer
SpawnTracerLog
TracerConfigureSamplePID
TracerConfigureOutDir
TracerConfigureOutPrefix
TracerConfigureInDir
TracerPrepareTrace
TracerRegisterRegions
TracerRegisterReactions
DisableReactions
TracerDebugSample
# this should be TracerNext?
TracerPrev
TracerDebugContinueInf
goto(decision)

tracer_finished:
# automatic switch to next
CloseTracer=(0:finish,1:debug_more)

debug_more:
TracerDebugContinueInf
goto(decision)

finish:
