#!/usr/bin/env python

from optparse import OptionParser

if __name__ == '__main__':
    parser = OptionParser()

    parser.add_option("-1", "--trace1", dest="trace1")
    parser.add_option("-2", "--trace2", dest="trace2")
    parser.add_option("-o", "--offset1", dest="offset1")
    parser.add_option("-p", "--offset2", dest="offset2")
    parser.add_option("-i", "--interval", dest="interval", default="1000000")

    (options, args) = parser.parse_args()

    if(options.interval == None):
        interval = 0
    else:
        interval = int(options.interval, 10)

    cextract_1 = open(options.trace1, 'r')
    cextract_2 = open(options.trace2, 'r')
    
    line_no = 0

    while True:
        try:
            line_1 = cextract_1.readline()
            line_2 = cextract_2.readline()
        except Exception as e:
            print e
            break

        if(line_1 == ''): break
        if(line_2 == ''): break

        try:
            src_1, instr_1_no = line_1.split()
        except ValueError:
            print 'Value error in source 1 at (%d) : %s, skipping' % (line_no, line_1)
            line_no = line_no + 1
            continue
    
        try:
            src_2, instr_2_no = line_2.split()
        except ValueError:
            print 'Value error in source 2 at (%d) : %s, skipping' % (line_no, line_2)
            line_no = line_no + 1
            continue
    
#        if(not src_1[-4:] == src_2[-4:]):
#            print "src diff"
        if(not src_1[-4:] == src_2[-4:]):
            print "Call source diff @ %d: %s (%s) - %s (%s)" % (line_no, src_1.strip(), instr_1_no, src_2.strip(), instr_2_no)
            break

        line_no = line_no + 1

        if(line_no % interval == 0x0):
            print 'Parsed %d lines' % line_no

    cextract_1.close()
    cextract_2.close()

