#!/usr/bin/env python

from optparse import OptionParser

if __name__ == '__main__':
    parser = OptionParser()

    parser.add_option("-1", "--trace1", dest="trace1")
    parser.add_option("-2", "--trace2", dest="trace2")
    parser.add_option("-o", "--offset1", dest="offset1")
    parser.add_option("-p", "--offset2", dest="offset2")
    parser.add_option("-i", "--interval", dest="interval", default="1000000")

    (options, args) = parser.parse_args()

    if(options.interval == None):
        interval = 0
    else:
        interval = int(options.interval, 10)

    cextract_1 = open(options.trace1, 'r')
    cextract_2 = open(options.trace2, 'r')
    
    line_no = 0

    while True:
        line_1 = cextract_1.readline()
        line_2 = cextract_2.readline()

        src_1, target_1 = line_1.split()
        src_2, target_2 = line_2.split()
    
        if(not src_1[-4:] == src_2[-4:]):
            print "src diff"
        if(not target_1[-4:] == target_2[-4:]):
            print "Target diff @ %d: %s - %s" % (line_no, target_1, target_2)
            break

        line_no = line_no + 1

        if(line_no % interval == 0x0):
            print 'Parsed %d lines' % line_no

    cextract_1.close()
    cextract_2.close()

