import statemachine
import usualparts.hs_logging
import usualparts.other_parts 
import usualparts.diagnostic
import usualparts.qemu_parts
import usualparts.disk_fs_parts
import usualparts.binner_parts
import generators

#
#
#
# ?decyzja
#test
#binner_key_wait
#binner_check_ready
#binner_start_logs
#binner_configure
#binner_spawn_app
#binner_spawn
#binner_kill_explorer
#fuzzing_loop
#qemu_connect_dev_socket
#binner_spawn_python_server
#qemu_mount_disks

Sleep = statemachine.State()
Sleep.name = "Sleeping"
Sleep.consequence = statemachine.Exit
Sleep.executing_routine = usualparts.other_parts.wait_10_seconds

BinnerKillExplorer = statemachine.State()
BinnerKillExplorer.name = "Killing explorer"
BinnerKillExplorer.consequence = Sleep
BinnerKillExplorer.executing_routine = usualparts.binner_parts.binner_kill_explorer

QemuConnectDevSocket = statemachine.State()
QemuConnectDevSocket.name = "Connecting socket"
QemuConnectDevSocket.consequence = BinnerKillExplorer
QemuConnectDevSocket.executing_routine = usualparts.qemu_parts.qemu_connect_dev_socket

BinnerSpawnPythonServer = statemachine.State()
BinnerSpawnPythonServer.name = "Spawning python server"
BinnerSpawnPythonServer.consequence = QemuConnectDevSocket
BinnerSpawnPythonServer.executing_routine = usualparts.binner_parts.binner_spawn_python_server

QemuMountDisks = statemachine.State()
QemuMountDisks.name = "Mounting qemu disks"
QemuMountDisks.consequence = BinnerSpawnPythonServer
QemuMountDisks.executing_routine = usualparts.qemu_parts.qemu_mount_disks

StartQemuFull = statemachine.State()
StartQemuFull.name = "Perform full Qemu start"
StartQemuFull.consequence = QemuMountDisks
StartQemuFull.executing_routine = usualparts.qemu_parts.qemu_start_full

AutogeneratedDisk = statemachine.State()
AutogeneratedDisk.name = "Create disk & autogenerate samples"
AutogeneratedDisk.consequence = StartQemuFull
AutogeneratedDisk.executing_routine = usualparts.disk_fs_parts.prepare_disk_autogenerated

AutogeneratedMethod = statemachine.State()
AutogeneratedMethod.name = "Generating saved using autogenerate"
AutogeneratedMethod.consequence = AutogeneratedDisk
AutogeneratedMethod.executing_routine = usualparts.disk_fs_parts.create_saved_disk_autogenerated

GlobMethod = statemachine.State()
GlobMethod.name = "Generating saved using glob"
GlobMethod.consequence = statemachine.Exit
GlobMethod.executing_routine = usualparts.disk_fs_parts.create_saved_disk_glob

def choosing_saved_disk_procedure():
    import globs
    options = globs.state.options

    if(options.samples_source == "autogenerated_batch"):
        return AutogeneratedMethod
    else:
        return GlobMethod

ChooseSavedMethod = statemachine.State()
ChooseSavedMethod.name = "Choosing method"
ChooseSavedMethod.consequence = None
ChooseSavedMethod.choosing_consequence = choosing_saved_disk_procedure
ChooseSavedMethod.executing_routine = usualparts.qemu_parts.qemu_bind_pipes

PreparePipes = statemachine.State()
PreparePipes.name = "Prepare pipes"
PreparePipes.consequence = ChooseSavedMethod
PreparePipes.executing_routine = usualparts.qemu_parts.qemu_bind_pipes

PrepareStats = statemachine.State()
PrepareStats.name = "Prepare stats"
PrepareStats.consequence = PreparePipes
PrepareStats.executing_routine = usualparts.diagnostic.prepare_stats

RegisterSignals = statemachine.State()
RegisterSignals.name = "Register signals"
RegisterSignals.consequence = PrepareStats
RegisterSignals.executing_routine = usualparts.other_parts.register_signals

EnableLogging = statemachine.State()
EnableLogging.name = "Enabling & testing logging"
EnableLogging.consequence = RegisterSignals
EnableLogging.executing_routine = usualparts.hs_logging.enable_logging

GetOptions = statemachine.State()
GetOptions.name = "Get options"
GetOptions.consequence = EnableLogging
GetOptions.executing_routine = usualparts.other_parts.get_options

PrintLogo = statemachine.State()
PrintLogo.name = "Print logo"
PrintLogo.consequence = GetOptions
PrintLogo.executing_routine = usualparts.other_parts.print_logo


